### ISSUE TITLE
¿Clases Pedido y Planta?

### ISSUE THREAD

**Issue by guillegregoret** [GiovaniFerraroTrivelli/tp-integrador#3]
Considero que no son necesarias las clases Pedido y Planta en el domino del trabajo, al menos no en esta etapa del TP.

https://github.com/GiovaniFerraroTrivelli/tp-integrador/blob/taller03/src/main/java/isi/died/tp/dominio/Pedido.java

https://github.com/GiovaniFerraroTrivelli/tp-integrador/blob/taller03/src/main/java/isi/died/tp/dominio/Planta.java

**Comment by GiovaniFerraroTrivelli** [comment]
Rechazado porque sos un bobo.

**Comment by guillegregoret** [comment]
> Rechazado porque sos un bobo.

:'v
